package:
  format-version: "1.0.0"
  name: "usb_apps_multi_controller"
  version: "v3.4.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "usb"
      type: "package"
      version: "v3.12.0"
    - name: "csp"
      type: "package"
      version: "v3.18.1"
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "bsp"
      type: "package"
      version: "v3.17.0"


