package:
  format-version: "1.0.0"
  name: "usb_apps_multi_controller"
  version: "v3.4.0-E1"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "usb"
      type: "package"
      version: "v3.11.0-E2"
    - name: "csp"
      type: "package"
      version: "v3.16.0"
    - name: "core"
      type: "package"
      version: "v3.12.0"
    - name: "bsp"
      type: "package"
      version: "v3.15.0"


