package:
  format-version: "1.0.0"
  name: "usb_apps_multi_controller"
  version: "v3.7.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "usb"
      type: "package"
      version: "v3.15.0"
    - name: "bsp"
      type: "package"
      version: "v3.21.1"


